"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { 
  ArrowLeft, Target, ShieldAlert, Activity, MapPin,
  Terminal, CheckCircle2, ChevronRight, FileText 
} from "lucide-react";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "";

export default function CampaignDossierPage() {
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;
  
  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    
    fetch(`${API_BASE}/api/campaigns/${id}`)
      .then(res => {
        if (!res.ok) throw new Error("Campaign not found");
        return res.json();
      })
      .then(json => {
        setData(json.campaign || json);
        setIsLoading(false);
      })
      .catch(err => {
        console.error(err);
        setError(err.message);
        setIsLoading(false);
      });
  }, [id]);

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center bg-[#020617]">
        <div className="text-slate-500 font-mono text-sm flex items-center gap-2">
          <Activity className="w-4 h-4 animate-spin text-cyan-500" />
          Loading Dossier {id}...
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="flex flex-col h-full bg-[#020617] p-6 text-slate-300">
        <button onClick={() => router.back()} className="flex items-center gap-2 text-slate-500 hover:text-white transition-colors mb-6 text-xs uppercase tracking-wider font-bold">
          <ArrowLeft className="w-4 h-4" /> Back to Campaigns
        </button>
        <div className="bg-red-900/20 border border-red-500/50 rounded p-6 text-red-400 font-mono">
          Error: {error || "Campaign not found"}
        </div>
      </div>
    );
  }

  const c = data.campaign || data;
  const entities = data.entities || c.entities || {};
  // The backend stores related_incident_ids (string ids) and campaign.techniques
  // / infrastructure / signatures — not the `related_incidents` / `mitre` objects
  // the first cut of this page assumed.
  const incidentIds: string[] = data.related_incident_ids || c.related_incident_ids || [];
  const techniques: string[] = c.techniques || [];
  const signatures: string[] = c.signatures || [];
  const domains: string[] = entities.domains || [];
  const confidence = c.confidence || 0;
  const fmtDate = (d?: string) => (d ? new Date(d).toLocaleString("sv") : null);
  
  let confColor = "text-emerald-400 border-emerald-500/30 bg-emerald-500/10";
  if (confidence > 0.8) confColor = "text-rose-400 border-rose-500/30 bg-rose-500/10";
  else if (confidence > 0.5) confColor = "text-amber-400 border-amber-500/30 bg-amber-500/10";

  return (
    <div className="flex flex-col h-full bg-[#020617] text-slate-300 font-sans overflow-y-auto">
      {/* Header */}
      <div className="p-4 border-b border-slate-800 bg-[#0F172A] shrink-0 sticky top-0 z-10">
        <div className="flex items-center gap-2 text-[10px] uppercase font-bold tracking-wider text-slate-500 mb-2">
          <Link href="/campaigns" className="hover:text-cyan-400 transition-colors flex items-center gap-1">
            <Target className="w-3.5 h-3.5" /> Campaigns
          </Link>
          <ChevronRight className="w-3 h-3" />
          <span className="text-slate-300">{id}</span>
        </div>
        
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-lg font-bold text-white flex items-center gap-3">
              {c.name || "Unnamed Campaign"}
              <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border ${confColor}`}>
                {Math.round(confidence * 100)}% Match
              </span>
            </h1>
            <p className="text-[10px] text-slate-400 font-mono mt-1">
              {fmtDate(c.first_seen) ? `First seen ${fmtDate(c.first_seen)}` : "Generated by CampaignIQ Analyzer"}
              {fmtDate(c.last_seen) && <span className="text-slate-500"> · Last seen {fmtDate(c.last_seen)}</span>}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button className="px-3 py-1.5 bg-[#020617] border border-slate-700 hover:bg-slate-800 text-slate-300 text-xs rounded transition-colors flex items-center gap-2 font-medium">
              <FileText className="w-3.5 h-3.5" /> Export Report
            </button>
            <button className="px-3 py-1.5 bg-rose-500/10 border border-rose-500/30 hover:bg-rose-500/20 text-rose-400 text-xs rounded transition-colors flex items-center gap-2 font-medium">
              <ShieldAlert className="w-3.5 h-3.5" /> Block IPs
            </button>
          </div>
        </div>
      </div>

      <div className="p-4 flex-1">
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-4 h-full items-start">
          
          {/* Main Info */}
          <div className="xl:col-span-2 space-y-4">
            
            {/* Executive Summary */}
            <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
              <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                <FileText className="w-3.5 h-3.5 text-cyan-500" /> Executive Summary
              </div>
              <div className="p-4 text-xs text-slate-300 leading-relaxed font-medium">
                <p>{c.description || "No description available for this campaign cluster."}</p>
              </div>
            </div>

            {/* MITRE ATT&CK */}
            <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
              <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Target className="w-3.5 h-3.5 text-rose-500" /> MITRE Techniques
                </span>
                <span className="font-mono text-slate-500 normal-case">{techniques.length}</span>
              </div>
              <div className="p-4">
                {techniques.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {techniques.map((tid, idx) => (
                      <span key={idx} className="px-2 py-1 bg-rose-500/10 border border-rose-500/30 rounded text-xs font-mono text-rose-300 uppercase">
                        {tid}
                      </span>
                    ))}
                  </div>
                ) : (
                  <span className="text-xs text-slate-500 font-mono">No MITRE techniques accumulated for this campaign yet.</span>
                )}
              </div>
            </div>

            {/* Related Incidents */}
            <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
              <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                <Activity className="w-3.5 h-3.5 text-cyan-500" /> Clustered Incidents ({incidentIds.length})
              </div>
              <div className="p-0">
                {incidentIds.length === 0 ? (
                  <div className="p-4 text-xs text-slate-500 font-mono">No incidents clustered in this campaign.</div>
                ) : (
                  <ul className="divide-y divide-slate-800">
                    {incidentIds.map((incId, i) => (
                      <li key={i}>
                        <Link
                          href={`/incidents/${incId}`}
                          className="flex items-center justify-between px-4 py-2.5 hover:bg-slate-800/20 transition-colors group"
                        >
                          <span className="font-mono text-xs text-cyan-400">{incId}</span>
                          <span className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-slate-500 group-hover:text-white transition-colors">
                            Inspect <ChevronRight className="w-3 h-3" />
                          </span>
                        </Link>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </div>

          </div>

          {/* Right Sidebar */}
          <div className="space-y-4">
            
            {/* Attribution */}
            <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
              <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                Attribution
              </div>
              <div className="p-4 space-y-4 text-xs">
                <div>
                  <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-1">Threat Actor</span>
                  <div className="flex items-center gap-2">
                    <ShieldAlert className="w-4 h-4 text-rose-500" />
                    <span className="text-white font-mono text-sm">{c.threat_actor || "Unknown"}</span>
                  </div>
                </div>
                <div>
                  <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 block mb-1">Target Geographies</span>
                  <div className="flex items-center gap-2 flex-wrap">
                    {c.targeted_countries?.length > 0 || entities.countries?.length > 0 ? (
                      (c.targeted_countries || entities.countries).map((country: string, i: number) => (
                        <span key={i} className="px-2 py-0.5 bg-[#020617] border border-slate-700 text-emerald-400 rounded flex items-center gap-1.5">
                          <MapPin className="w-3 h-3" /> {country}
                        </span>
                      ))
                    ) : (
                      <span className="text-slate-500 font-mono">Global / Unknown</span>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* Indicators of Compromise */}
            <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
              <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                Attacker Infrastructure
              </div>
              <div className="p-4 space-y-1">
                {entities.ips && entities.ips.length > 0 ? (
                  entities.ips.map((ip: string, i: number) => (
                    <div key={i} className="flex items-center justify-between px-2 py-1.5 bg-[#020617] rounded border border-slate-800 hover:border-slate-700">
                      <span className="font-mono text-xs text-purple-400">{ip}</span>
                      <span className="text-[9px] uppercase text-slate-500 font-bold tracking-wider">IPv4</span>
                    </div>
                  ))
                ) : (
                  <span className="text-xs text-slate-500 font-mono">No IP observables found.</span>
                )}
                {domains.map((d, i) => (
                  <div key={`d-${i}`} className="flex items-center justify-between px-2 py-1.5 bg-[#020617] rounded border border-slate-800 hover:border-slate-700">
                    <span className="font-mono text-xs text-emerald-400 truncate">{d}</span>
                    <span className="text-[9px] uppercase text-slate-500 font-bold tracking-wider">Domain</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Detection Signatures */}
            {signatures.length > 0 && (
              <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
                <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                  Detection Signatures
                </div>
                <div className="p-4 space-y-1">
                  {signatures.map((s, i) => (
                    <div key={i} className="px-2 py-1.5 bg-[#020617] rounded border border-slate-800 text-[10px] font-mono text-amber-300/90 break-words">
                      {s}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Mitigations */}
            <div className="bg-[#0F172A] border border-slate-800 rounded overflow-hidden">
              <div className="px-4 py-2 bg-[#0A0F1C] border-b border-slate-800 text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Suggested Mitigation
              </div>
              <div className="p-4 text-xs">
                {c.mitigation_steps && c.mitigation_steps.length > 0 ? (
                  <ul className="space-y-3">
                    {c.mitigation_steps.map((step: string, i: number) => (
                      <li key={i} className="flex items-start gap-2 text-slate-300">
                        <Terminal className="w-3.5 h-3.5 text-emerald-500 shrink-0 mt-0.5" />
                        <span>{step}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <span className="text-slate-500 font-mono">Run SOAR orchestration for automated mitigation plan.</span>
                )}
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
